<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import { Bot } from 'lucide-vue-next'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { useLangStore } from '@/stores/lang'

const langStore = useLangStore()

const copy = computed(() => {
  const no = langStore.language === 'no'
  return {
    title: no ? 'Du snakker med en AI-assistent' : 'You are chatting with an AI assistant',
    body: no
      ? 'Svarene er generert av en språkmodell, ikke Kevin personlig. De kan være unøyaktige eller utdaterte.'
      : 'Replies are generated by a language model, not Kevin in person. They may be inaccurate or out of date.',
    learnMore: no ? 'Les mer i personvernerklæringen' : 'Read more in the privacy policy',
  }
})
</script>

<template>
  <Alert class="border-blue-200 bg-blue-50/90 text-blue-950" role="note">
    <Bot class="size-4 shrink-0 text-blue-700" aria-hidden="true" />
    <AlertTitle class="text-blue-900">{{ copy.title }}</AlertTitle>
    <AlertDescription class="text-blue-800">
      <p>{{ copy.body }}</p>
      <RouterLink
        to="/privacy-policy"
        class="mt-2 inline-block text-sm font-medium text-blue-700 underline underline-offset-2 hover:text-blue-900"
      >
        {{ copy.learnMore }}
      </RouterLink>
    </AlertDescription>
  </Alert>
</template>
