<script setup lang="ts">
import { useRouter } from 'vue-router'
import { ref, computed, onMounted } from 'vue'
import { useLangStore } from '../stores/lang'
import { useChatModelStore } from '../stores/model'
import { ChatModelOptionProvider } from '@/api/generated/portfolio'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Info, Github, Linkedin, MessageSquare, ChevronRight } from 'lucide-vue-next'

const router = useRouter()

const langStore = useLangStore()
const chatModelStore = useChatModelStore()

const language = computed({
  get: () => langStore.language,
  set: (v: 'en' | 'no') => langStore.setLanguage(v),
})

const questionsByLang: Record<'en' | 'no', string[]> = {
  en: [
    'Why did Kevin create this website?',
    'Which courses has Kevin taken?',
    'Which projects has Kevin worked on?',
    'Who is Kevin?',
  ],
  no: [
    'Hvorfor lagde Kevin denne nettsiden?',
    'Hvilke emner har Kevin hatt?',
    'Hvilke prosjekter har Kevin jobbet med?',
    'Hvem er Kevin?',
  ],
}

const visibleQuestions = computed(() => questionsByLang[language.value])

const chatDisclaimer = computed(() => {
  if (language.value === 'no') {
    return {
      title: 'Før du chatter',
      body:
        'Svar genereres av en AI-modell og kan være feil eller hallusinerte. Ikke del private eller sensitive opplysninger i chatten.',
    }
  }
  return {
    title: 'Before you chat',
    body:
      'Replies are generated by an AI model and may be inaccurate or hallucinated. Do not share private or sensitive information in the chat.',
  }
})

const feedbackInvite = computed(() => {
  if (language.value === 'no') {
    return {
      body: 'Jeg setter stor pris på tilbakemeldinger, slik at jeg kan forbedre prosjektet.',
      cta: 'Gi tilbakemelding',
      ariaLabel: 'Gå til tilbakemeldingsskjema',
    }
  }
  return {
    body: "I'd really appreciate your feedback so I can keep improving this project.",
    cta: 'Share feedback',
    ariaLabel: 'Go to the feedback form',
  }
})

const quickQuestion = ref('')

const providerLabels = computed(() =>
  language.value === 'no'
    ? { heading: 'AI-leverandør', openai: 'OpenAI', anthropic: 'Anthropic' }
    : { heading: 'AI provider', openai: 'OpenAI', anthropic: 'Anthropic' },
)

const modelLabel = computed(() => (language.value === 'no' ? 'Modell' : 'Model'))

const modelsForActiveProvider = computed(() => {
  const p = chatModelStore.activeProvider
  if (!p) return chatModelStore.models
  return chatModelStore.modelsForProvider(p)
})

const selectedModelId = computed({
  get: () => chatModelStore.selectedModelId,
  set: (id: string) => chatModelStore.setSelectedModelId(id),
})

const showProviderToggle = computed(
  () => chatModelStore.hasOpenAI && chatModelStore.hasAnthropic,
)

onMounted(() => {
  void chatModelStore.ensureModelsLoaded()
})

function ask(q: string) {
  router.push({ name: 'chat', query: { q } })
}

function submitQuick() {
  const q = quickQuestion.value.trim()
  if (!q) return
  ask(q)
}
</script>

<template>
  <main class="relative flex min-h-0 flex-1 flex-col overflow-y-auto bg-gradient-to-br from-slate-50 to-slate-100 pt-20">
    <!-- Gradient Background Overlay -->
    <div class="absolute inset-0 pointer-events-none">
      <div class="absolute top-0 left-0 w-full h-full" style="background: radial-gradient(circle at 20% 80%, rgba(59, 130, 246, 0.1) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(37, 99, 235, 0.1) 0%, transparent 50%);"></div>
    </div>

    <!-- Blue Blob Shapes -->
    <div class="blob-container">
      <div class="blob blob-1"></div>
      <div class="blob blob-2"></div>
      <div class="blob blob-3"></div>
      <div class="blob blob-4"></div>
      <div class="blob blob-5"></div>
      <div class="blob blob-6"></div>
    </div>

    <!-- Main Content - Centered -->
    <div class="relative z-10 flex min-h-full flex-col items-center justify-center px-4 py-8">
      <div class="flex flex-col items-center space-y-8">
        <section class="brand">
          <h1 class="mb-4 px-1 text-center text-4xl font-bold sm:text-5xl md:text-6xl lg:text-7xl">
            Kevin's <span class="bg-gradient-to-r from-blue-600 via-blue-700 to-blue-800 bg-clip-text text-transparent animate-gradient-x">AI</span>.
          </h1>
          <div class="flex justify-center">
            <div class="relative rounded-full p-1 flex bg-gradient-to-r from-slate-200 to-slate-300 shadow-md border-2 border-transparent bg-clip-padding">
              <div
                class="absolute top-1 bottom-1 w-16 rounded-full shadow-lg transition-transform duration-300 ease-in-out bg-gradient-to-r from-white to-slate-50 border border-blue-200"
                :class="language === 'en' ? 'translate-x-0' : 'translate-x-16'"
              ></div>
              <button
                class="relative z-10 w-16 py-2 text-sm font-medium transition-all duration-300 cursor-pointer rounded-full overflow-hidden"
                :class="language === 'en' ? 'text-blue-700 font-semibold' : 'text-gray-500'"
                @click="language = 'en'"
              >
                EN
              </button>
              <button
                class="relative z-10 w-16 py-2 text-sm font-medium transition-all duration-300 cursor-pointer rounded-full overflow-hidden"
                :class="language === 'no' ? 'text-blue-700 font-semibold' : 'text-gray-500'"
                @click="language = 'no'"
              >
                NO
              </button>
            </div>
          </div>

          <!-- Provider + model (same session keys as chat page) -->
          <div
            v-if="chatModelStore.models.length > 0"
            class="mt-6 flex flex-col items-center gap-4 w-full max-w-md px-2"
          >
            <p class="text-xs font-medium uppercase tracking-wide text-slate-500">
              {{ providerLabels.heading }}
            </p>
            <div v-if="showProviderToggle" class="flex justify-center w-full">
              <div
                class="relative rounded-full p-1 flex bg-gradient-to-r from-slate-200 to-slate-300 shadow-md border-2 border-transparent bg-clip-padding"
              >
                <div
                  class="absolute top-1 bottom-1 w-28 rounded-full shadow-lg transition-transform duration-300 ease-in-out bg-gradient-to-r from-white to-slate-50 border border-blue-200"
                  :class="
                    chatModelStore.activeProvider === ChatModelOptionProvider.OPENAI
                      ? 'translate-x-0'
                      : 'translate-x-28'
                  "
                ></div>
                <button
                  type="button"
                  class="relative z-10 w-28 py-2 text-sm font-medium transition-all duration-300 cursor-pointer rounded-full overflow-hidden"
                  :class="
                    chatModelStore.activeProvider === ChatModelOptionProvider.OPENAI
                      ? 'text-blue-700 font-semibold'
                      : 'text-gray-500'
                  "
                  :disabled="!chatModelStore.hasOpenAI"
                  @click="chatModelStore.selectFirstForProvider(ChatModelOptionProvider.OPENAI)"
                >
                  {{ providerLabels.openai }}
                </button>
                <button
                  type="button"
                  class="relative z-10 w-28 py-2 text-sm font-medium transition-all duration-300 cursor-pointer rounded-full overflow-hidden"
                  :class="
                    chatModelStore.activeProvider === ChatModelOptionProvider.ANTHROPIC
                      ? 'text-blue-700 font-semibold'
                      : 'text-gray-500'
                  "
                  :disabled="!chatModelStore.hasAnthropic"
                  @click="chatModelStore.selectFirstForProvider(ChatModelOptionProvider.ANTHROPIC)"
                >
                  {{ providerLabels.anthropic }}
                </button>
              </div>
            </div>
            <div class="flex flex-col gap-2 w-full">
              <label
                for="home-model-select"
                class="text-center text-xs font-medium uppercase tracking-wide text-slate-500"
              >
                {{ modelLabel }}
              </label>
              <select
                id="home-model-select"
                v-model="selectedModelId"
                class="w-full rounded-lg border-2 border-blue-200/40 bg-white/90 px-3 py-2 text-sm text-slate-800 focus:border-blue-400 focus:outline-none"
              >
                <option v-for="m in modelsForActiveProvider" :key="m.id" :value="m.id">
                  {{ m.label }} ({{ m.provider }})
                </option>
              </select>
            </div>
          </div>
        </section>

        <section class="quick">
          <div class="grid w-full max-w-2xl grid-cols-1 gap-4 sm:grid-cols-2">
            <button
              v-for="q in visibleQuestions"
              :key="q"
              class="relative overflow-hidden rounded-xl border border-gray-200 bg-white p-4 text-left transition-all duration-300 hover:border-blue-300 hover:shadow-xl group hover:bg-gradient-to-br hover:from-white/90 hover:to-slate-50/90 hover:backdrop-blur-sm sm:p-6"
              @click="ask(q)"
            >
              <div class="text-gray-800 font-medium text-sm leading-relaxed group-hover:text-gray-900 transition-colors duration-300 cursor-pointer">
                {{ q }}
              </div>
            </button>
          </div>
        </section>
      </div>
    </div>

    <!-- Chat area: inline disclaimer, links, and input -->
    <div class="pb-8 flex-shrink-0 relative z-10 w-full max-w-2xl mx-auto px-4 space-y-3">
      <Alert
        class="border-blue-200/80 bg-blue-50/90 text-slate-800 shadow-sm backdrop-blur-sm [&>svg]:text-blue-600"
      >
        <Info class="size-4 shrink-0" aria-hidden="true" />
        <AlertTitle>{{ chatDisclaimer.title }}</AlertTitle>
        <AlertDescription>
          <p>{{ chatDisclaimer.body }}</p>
        </AlertDescription>
      </Alert>

      <div class="flex justify-center gap-3">
        <a
          href="https://github.com/kdm-kev-NTNU"
          target="_blank"
          rel="noopener noreferrer"
          class="inline-flex h-10 w-10 items-center justify-center rounded-full border border-gray-200 bg-white text-gray-700 shadow-sm transition hover:border-gray-300 hover:bg-slate-50 hover:text-gray-900"
          :aria-label="language === 'en' ? 'Kevin on GitHub' : 'Kevin på GitHub'"
        >
          <Github class="size-5" />
        </a>
        <a
          href="https://linkedin.com/in/kevin-dennis-mazali/"
          target="_blank"
          rel="noopener noreferrer"
          class="inline-flex h-10 w-10 items-center justify-center rounded-full border border-gray-200 bg-white text-blue-700 shadow-sm transition hover:border-blue-200 hover:bg-blue-50"
          :aria-label="language === 'en' ? 'Kevin on LinkedIn' : 'Kevin på LinkedIn'"
        >
          <Linkedin class="size-5" />
        </a>
      </div>

      <form class="flex gap-3 max-w-md mx-auto relative bg-white/90 backdrop-blur-sm border-2 border-blue-200/20 rounded-xl p-2 transition-all duration-300 hover:border-blue-300/40 hover:bg-white/95 hover:shadow-lg hover:shadow-blue-500/15 focus-within:border-blue-300/60 focus-within:bg-white/98 focus-within:shadow-lg focus-within:shadow-blue-500/25" @submit.prevent="submitQuick">
        <Input
          v-model="quickQuestion"
          type="text"
          class="flex-1 bg-white/80 border-2 border-blue-200/20 rounded-lg transition-all duration-300 focus:bg-white/95 focus:border-blue-300/50 focus:shadow-sm focus:shadow-blue-500/10 focus:outline-none placeholder:text-blue-600/60 placeholder:font-medium"
          :placeholder="language === 'en' ? `Curious? Kevin's AI is here to answer!` : `Nysgjerrig? Kevin sin AI svarer gjerne!`"
        />
        <Button type="submit" class="cursor-pointer bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-semibold hover:-translate-y-0.5 hover:shadow-lg hover:shadow-blue-500/40 transition-all duration-300 relative overflow-hidden">Send →</Button>
      </form>
    </div>

    <!-- Mobile: compact FAB-style feedback; sm+: card with copy -->
    <RouterLink
      to="/feedback"
      class="feedback-corner group fixed bottom-4 left-3 z-[60] flex items-center justify-center rounded-full border-2 border-blue-300/70 bg-white/95 p-3 shadow-lg shadow-blue-900/10 ring-1 ring-blue-500/15 backdrop-blur-md transition hover:-translate-y-0.5 hover:border-blue-500 hover:bg-white hover:shadow-xl hover:shadow-blue-500/20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 sm:bottom-6 sm:left-5 sm:max-w-[min(20.5rem,calc(100vw-1.5rem))] sm:items-start sm:justify-start sm:gap-4 sm:rounded-2xl sm:p-4"
      :aria-label="feedbackInvite.ariaLabel"
    >
      <div
        class="flex size-12 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-blue-700 text-white shadow-md sm:size-16 sm:rounded-xl"
        aria-hidden="true"
      >
        <MessageSquare class="size-7 sm:size-9" stroke-width="2" />
      </div>
      <div class="hidden min-w-0 flex-1 pt-0.5 text-left sm:block">
        <p class="text-sm font-medium leading-snug text-slate-800 sm:text-[0.95rem] sm:leading-snug">
          {{ feedbackInvite.body }}
        </p>
        <span
          class="mt-2 inline-flex items-center gap-0.5 text-sm font-semibold text-blue-700 transition group-hover:text-blue-900"
        >
          {{ feedbackInvite.cta }}
          <ChevronRight class="size-4 shrink-0" aria-hidden="true" />
        </span>
      </div>
    </RouterLink>
  </main>
</template>

<style scoped>
@keyframes gradient-x {
  0%, 100% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
}

@keyframes float {
  0%, 100% {
    transform: translate(0, 0) scale(1);
  }
  25% {
    transform: translate(20px, -30px) scale(1.1);
  }
  50% {
    transform: translate(-15px, -20px) scale(0.9);
  }
  75% {
    transform: translate(-25px, 10px) scale(1.05);
  }
}

.animate-gradient-x {
  background-size: 200% 200%;
  animation: gradient-x 3s ease-in-out infinite;
}

/* Blue Blob Shapes */
.blob-container {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  pointer-events: none;
  overflow: hidden;
  z-index: 1;
}

.blob {
  position: absolute;
  border-radius: 50%;
  filter: blur(40px);
  animation: float 6s ease-in-out infinite;
}

.blob-1 {
  width: 300px;
  height: 300px;
  background: radial-gradient(circle, rgba(59, 130, 246, 0.6) 0%, rgba(37, 99, 235, 0.5) 50%, transparent 70%);
  top: 10%;
  left: 5%;
  animation-delay: 0s;
  animation-duration: 8s;
}

.blob-2 {
  width: 200px;
  height: 200px;
  background: radial-gradient(circle, rgba(96, 165, 250, 0.55) 0%, rgba(59, 130, 246, 0.5) 50%, transparent 70%);
  top: 60%;
  right: 10%;
  animation-delay: 2s;
  animation-duration: 10s;
}

.blob-3 {
  width: 250px;
  height: 250px;
  background: radial-gradient(circle, rgba(37, 99, 235, 0.6) 0%, rgba(29, 78, 216, 0.5) 50%, transparent 70%);
  top: 30%;
  right: 20%;
  animation-delay: 4s;
  animation-duration: 7s;
}

.blob-4 {
  width: 180px;
  height: 180px;
  background: radial-gradient(circle, rgba(147, 197, 253, 0.65) 0%, rgba(96, 165, 250, 0.55) 50%, transparent 70%);
  bottom: 20%;
  left: 15%;
  animation-delay: 1s;
  animation-duration: 9s;
}

.blob-5 {
  width: 220px;
  height: 220px;
  background: radial-gradient(circle, rgba(29, 78, 216, 0.6) 0%, rgba(30, 64, 175, 0.5) 50%, transparent 70%);
  top: 70%;
  left: 60%;
  animation-delay: 3s;
  animation-duration: 11s;
}

.blob-6 {
  width: 160px;
  height: 160px;
  background: radial-gradient(circle, rgba(59, 130, 246, 0.7) 0%, rgba(37, 99, 235, 0.6) 50%, transparent 70%);
  top: 15%;
  left: 70%;
  animation-delay: 5s;
  animation-duration: 6s;
}

/* Decorative blobs — smaller blur/size on narrow viewports */
@media (max-width: 768px) {
  .blob {
    filter: blur(30px);
  }

  .blob-1,
  .blob-3 {
    width: 200px;
    height: 200px;
  }

  .blob-2,
  .blob-4,
  .blob-5 {
    width: 150px;
    height: 150px;
  }

  .blob-6 {
    width: 120px;
    height: 120px;
  }
}
</style>
