spring:
  application:
    name: portfolio
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          # Limit completion tokens per response
          max-tokens: 400
      embedding:
        options:
          model: text-embedding-3-large
          dimensions: 3072
  datasource:
    url: jdbc:mysql://localhost:3307/aboutme?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8080}
sfg:
  aiapp:
    # Vector store plasseres alltid under 'backend/vectordatabase' uavhengig av working dir
    # Denne veien tolkes som relativ til backend av appen (ikke prosessens cwd)
    vectorStorePath: vectordatabase/vectorstore.json
    encryptContent: true
    encryptionKeyBase64: ${VECTORSTORE_ENC_KEY}
    documentsToLoadDir: classpath:/tmp/docs/


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE




