spring:
  application:
    name: portfolio
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-large
          dimensions: 3072
sfg:
  aiapp:
    # runtime-fil på rotnivå i prosjektet
    vectorStorePath: ./vectordatabase/vectorstore.json
    encryptContent: true
    encryptionKeyBase64: ${VECTORSTORE_ENC_KEY}
    documentsToLoadDir: classpath:/tmp/docs/




